require 'nokogiri'
require 'open-uri'

desc "Adds events"
task add_events: :environment do
  # test.html is from http://www.experiencecolumbus.com/event-search?keyword=&sdate=04%2F17%2F15&edate=04%2F19%2F15&free=&cat=9&start=1
  # all the events are generated by javascript so it doesn't do us any good to grab it form the URL since nokogiri doesn't run the js

  #<Event id: nil, start_date: nil, end_date: nil, location: nil, name: nil, price: nil, description: nil, link: nil, created_at: nil, updated_at: nil>

  # TODO: fix the js problem

  @doc = Nokogiri::HTML(open(File.expand_path('lib/tasks/test.html')))
  scrapedInfo = Array.new

  title = @doc.css(".results").css("li").each do |node|
    scrapedInfo.push(node)
  end

  scrapedInfo.each do |node|
    if !node.css('h3').text.empty? then
      event = Event.new

      event.name = node.css('h3').text # Gets Name

      location = node.css('h4').text
      location = location + ", " + node.css('ul > li > a').text
      event.location = location

      event.start_date = Date.strptime(node.css('.dtstart').text, '%m-%d-%Y')

      if node.css('.dtend').text.empty? then
        event.end_date = event.start_date
      else
        event.end_date = Date.strptime(node.css('.dtend').text, '%m-%d-%Y')
      end

      page = node.css('h3 > a')
      event.link = page[0]['href']

      event.save
    end
  end
end
